GET http://localhost:8080/auth/test
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJHT09HTEVfMTA1NDg5NjM5OCIsImV4cCI6MTcwNjQyNDkzMywiaWF0IjoxNzA2NDI0MDMzLCJpc3MiOiJmYXJtaWx5Iiwicm9sZXMiOiJVU0VSIn0.dG9on6nOHfWvOUKnMDNBW4IKnpmwr_c1ETd4-g6IMYKjYDxnvQVAKgGwSjy8WcwVzy0AIwBSDl0Aq4CU9JeSdA